name: test_as_ros_pkg

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, NOT_TEST_BUILD: true }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
